spring:
  datasource:
    url: jdbc:mysql://remotemysql.com/hgWj7Gqbms?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: hgWj7Gqbms
    password: 9Fdrs8NTyH
    driverClassName: com.mysql.cj.jdbc.Driver
